# Generated by Django 5.2.14 on 2026-05-10 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='doctors.medecin'),
        ),
        migrations.AddField(
            model_name='datebloquee',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_bloquees', to='doctors.medecin'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='doctors.specialite'),
        ),
        migrations.AlterUniqueTogether(
            name='datebloquee',
            unique_together={('medecin', 'date')},
        ),
    ]
